version: "3.8"

services:
    postgres:
        image: postgres
        container_name: dev_postgres
        environment:
            POSTGRES_USER: devuser
            POSTGRES_PASSWORD: devpass
            POSTGRES_DB: devdb
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    minio:
        image: "minio/minio:latest"
        container_name: dev_minio
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        command: server /data --console-address ":9001"
        ports:
            - "9000:9000" # API S3 compatible
            - "9001:9001" # Interface web (console)
        volumes:
            - miniodata:/data

volumes:
    pgdata:
    miniodata:
