# Dockfile pour le backend en mode production
# Étape 1: Build
FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY ./ ./

RUN npm run build

# Étape 2: Image finale
FROM node:22-alpine AS production

WORKDIR /app

COPY package*.json ./

RUN npm ci --only=production

COPY --from=build /app/dist ./dist
COPY ./db ./db

EXPOSE 3000

CMD ["node", "dist/index.js"]