version: '3.8'
# Fichier Docker Compose pour la production.
# Veiller à ce que le fichier .env soit configuré avec les bonnes variables d'environnement.
services:
  db:
    image: postgres
    container_name: prod_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: studysen_api
    restart: unless-stopped
    image: docker.io/appenisen/studysen_api:latest
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    container_name: espace_clubs
    restart: unless-stopped
    image: docker.io/appenisen/studysen_espace_clubs:latest
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
